### ISSUE TITLE
Noting is rendered

### ISSUE THREAD

**Issue by tedbeer** [VladimirKalachikhin/Galadriel-map#2]
I used your Raspberrypi image. After fixing [a networking issue](https://github.com/VladimirKalachikhin/GaladrielMap-Demo-image/discussions/4) I opened a map. I selected OpenSeaMap in menu but it renders nothing. Entering random tiles in Download menu started downloading something - I see that mounted **/tiles** occupies already 463Mb but the map is not rendered. The whole page space remains grey. Browser development tools shows massive 404s:
 
![image](https://user-images.githubusercontent.com/822497/117536399-180ba300-affb-11eb-8175-7db38358ee6a.png)

**Comment by VladimirKalachikhin** [comment]
I hope you're all right now?
