### ISSUE TITLE
Localization is not complete

### ISSUE THREAD

**Issue by tedbeer** [VladimirKalachikhin/Galadriel-map#3]
I switched to English language by editing **internationalization.php** and **dashboard.php** and I've noticed that not all text strings are translated.
![image](https://user-images.githubusercontent.com/822497/117540864-7e9bbb80-b011-11eb-95da-9eae6df5a2f8.png)
![image](https://user-images.githubusercontent.com/822497/117540985-0aade300-b012-11eb-8f46-f4a7e60eb311.png)

Ideally I'd expect to have a language switch in UI or at least having it configurable in a single place ( params.php ?)

**Comment by VladimirKalachikhin** [comment]
It's not a bug, it is a feature. 
Additional info for the international crew.

The language of UI depends on the browser locale. If ru -- Russian, else -- English. Let me know if not is it.
